### PR TITLE
prevent missing id php notice array flip

### PR DESCRIPTION
**Pull request by youpixxl**

### CODE REVIEW

**Comment by youpixxl** [comment]
Hi Philippe
Just a small PR to fix php notice which crash VRT during update :-)

**Comment by pvbergen** [comment]
Is this also valid for 2.x? If so, we need a second PR to 2.x :)

**Comment by pvbergen** [comment]
@danielwirz 
Can we remove the dependency to iq_group from this module or move it to a submodule?

**Comment by danielwirz** [comment]
this is no longer needed since we remove iq_group functionalty from the module

**Pull request closed without merging**
